
build-back:
  image: maven:3.6.2-jdk-11
  stage: build
  script:
    - cd game-backend
    - mvn clean package

build-front:
  image: node:12.18.3
  stage: build
  script:
    - cd game-frontend
    - npm install
    - npm run ng build --prod --build-optimizer

